### PR TITLE
refactor(standards): add standards and update the code

### PR DESCRIPTION
**Pull request by stojanovic**
This commit is adding JS standards and editor config and refactoring scripts from bin folder and siteInfo.js to match those standards. It's also adding a check for standards when you run 'npm start' and badge to readme. This is not a best way to check if standards are ok, but it's a beginning.

### CODE REVIEW

**Comment by stojanovic** [comment]
cc @simalexan @gorangajic

**Comment by gorangajic** [comment]
u tom standardu mi se bas ne 2 spejsa, ali sta da se radi :smile:

**Comment by stojanovic** [comment]
Koristiš 4 ili tabove?
Imaš [editor config](http://editorconfig.org) i on to reši za tebe, ne moraš sam da menjaš.

Može i neki drugi ako hoćete, meni je sve jedno dok god imamo nešto.

**Comment by gorangajic** [comment]
nema veze, merguj slobodno ne moze se svima udovoljiti :smiley:

**Comment by simalexan** [comment]
pre sam i ja koristio tab kao delimiter ~ 4 space-a, ali sam pre 2 godine poceo sa 2 space-a i zadovoljan sam. kada je reicmo complex DOM tree, mozes bas dosta vise da vidis

**Pull request merged**
