### PR TITLE
add commitizen

### PR DESCRIPTION
**Pull request by gorangajic**
I have noticed that @stojanovic use angular commit message style so I have added commitizen

### CODE REVIEW

**Comment by stojanovic** [comment]
:+1: 
I never used it before, but it looks good.

**Comment by simalexan** [comment]
yep looks good, nice one @gorangajic

**Comment by gorangajic** [comment]
@stojanovic haha and I thought you are using it but just local version or something like that because your commits are the same like in angular

**Comment by stojanovic** [comment]
@gorangajic As I told you yesterday I am typing them manually all the time :D
But this will speed that up and I'll definitely start using it on CH projects :)

**Pull request merged**
